### ISSUE TITLE
mqtt_bridge install

### ISSUE THREAD

**Issue by 1140464BV** [groove-x/mqtt_bridge#14]
Hello,

I'm having currently issues while installing mqtt_bridge... Following the readme, I installed all dependencies referred, but after downloading the folder and running:

roslaunch mqtt_bridge demo.launch

I get the following output:
[demo.launch] is neither a launch file in package [mqtt_bridge] nor is [mqtt_bridge] a launch file name

Can anyone help on this?

 Best regards,
BV

**Comment by welkerCode** [comment]
I am getting something similar.  Following the same procedure as @1140464BV , but I get 

Traceback (most recent call last):
    File "/home/pi/catkin_workspace/src/mqtt_bridge/scripts/mqtt_bridge_node.py", line 5, in <module> 
        from mqtt_bridge.app import mqtt_bridge_node
ImportError: No module named mqtt_bridge.app

Any tips?

**Comment by fabolhak** [comment]
I got the same error on Ubuntu 16.04 and kinetic when trying to install from my workspace. 

I got it working with installing the system package instead:

`sudo apt install ros-kinetic-mqtt-bridge`

This works for me (after removing bson which I installed via pip).

**Comment by mjforan** [comment]
After installing a package, you must add it to your environment. In the /install and /devel folders there is a "setup.bash" file. You need to add one of these by writing it's path at the bottom of ~/.bashrc

**Comment by PrimeshShamilka** [comment]
After installing the dependencies, first you have to build mqtt_bridge using catkin_make, then you have to source the environment variables.

cd into mqtt_bridge directory and type the following commands. 
` catkin_make `
` source devel/setup.bash `
