### ISSUE TITLE
Unable to change format of topic before sending to remote server

### ISSUE THREAD

**Issue by kauffmanes** [groove-x/mqtt_bridge#16]
I got this set up to listen for messages on a topic and forward them to a remote server using the JSON format and it's working great. I would ideally like to change the format before it's sent to a remote server. For example, instead of `{ "topic1": "123" }`, is there a way to send it out like `{"topic": "topic1", "value": "123"}`?

**Comment by ledmonster** [comment]
to do so, please implement custom Bridge class and use it. See `mqtt_bridge.bridge` module. thank you.
