### ISSUE TITLE
Question: how to bridge  complex messages like cmd_vel

### ISSUE THREAD

**Issue by Luke1962** [groove-x/mqtt_bridge#20]
Please can you explain how to bridge  complex messages like cmd_vel (geometry_msgs/Twist)?
Thank you in advance

**Comment by mhaboali** [comment]
A similar need here. I'd like to bridge the sensor_msgs/Imu data.

**Comment by martinwimpff** [comment]
`msg_type: geometry_msgs.msg:Twist`

**Comment by PrimeshShamilka** [comment]
You can simply define the complex message type in demo_params.yaml. 

` factory: mqtt_bridge.bridge:RosToMqttBridge`
` msg_type: sensor_msgs.msg:Imu`
` topic_from: imu`
` topic_to: ping`
` factory: mqtt_bridge.bridge:MqttToRosBridge`
` msg_type: sensor_msgs.msg:Imu`
`topic_from: ping`
` topic_to: /pong`
