### ISSUE TITLE
Why don't you use rosdep?

### ISSUE THREAD

**Issue by hakuturu583** [groove-x/mqtt_bridge#22]
In your description, you use requirements.txt for solving dependency.
However, ros has it's own dependency solving system called rosdep.
Why do you use requirements.txt?

**Comment by PrimeshShamilka** [comment]
I think you can find the answer here,
https://answers.ros.org/question/236249/rosdep-equivalent-of-pip-freeze-and-pip-install-requirementstxt/

**Comment by ledmonster** [comment]
related PR: #23, thank you @hakuturu583.
