### ISSUE TITLE
Convert ROS service to MQTT

### ISSUE THREAD

**Issue by CaptD** [groove-x/mqtt_bridge#48]
First of all, thanks to the developers for this great work. It provides a useful bridge between ROS topic and MQTT.

I have no problem compiling and running the demo. But I do have a question about conversion between ROS service and MQTT. 
There are two methods in my mind:
1. convert a ROS service to a topic and set its QoS to be 2

or 

2. convert a ROS service to two topics bidirectionally, and use their member variables to reproduce "request - response" logic.
Considering the network status is unstable, and I don't want a service being called twice after reconnecting, such as reset an actuator. What is the best practice? Do you have any suggestion?

Thanks.

**Comment by pavloblindnology** [comment]
You can extend mqtt_bridge with a custom Bridge plugin for services.

**Comment by ledmonster** [comment]
@CaptD Interesting. Thank you for providing a new idea. But currently, I can't work on new functionalities. as @pavloblindnology says, please implement a custom Bridge plugin on your project.
