### ISSUE TITLE
when i input roslaunch mqtt_bridge demo.launch

### ISSUE THREAD

**Issue by 975150313** [groove-x/mqtt_bridge#50]
When I run roslaunch mqtt_bridge demo.launch in docker, he prompts me：
RLException: [demo.launch] is neither a launch file in package [mqtt_bridge] nor is [mqtt_bridge] a launch file name
The traceback for the exception was written to the log file

The docker is  ros:noetic
and I setup  ros-noetic-rosbridge-suite，the roslaunch rosbridge_server rosbridge_websocket.launch is working
what should I do？

**Comment by bindu030** [comment]
> The docker is ros:noetic and I setup ros-noetic-rosbridge-suite，the roslaunch rosbridge_server rosbridge_websocket.launch is working what should I do？

How you are able to ahceive this?

**Comment by bindu030** [comment]
> When I run roslaunch mqtt_bridge demo.launch in docker, he prompts me： RLException: [demo.launch] is neither a launch file in package [mqtt_bridge] nor is [mqtt_bridge] a launch file name The traceback for the exception was written to the log file
> 
> The docker is ros:noetic and I setup ros-noetic-rosbridge-suite，the roslaunch rosbridge_server rosbridge_websocket.launch is working what should I do？

**Comment by ledmonster** [comment]
@975150313 Probably you should run
```
source ~/catkin_ws/devel/setup.bash
```
again.
