### ISSUE TITLE
How to turn off serialization

### ISSUE THREAD

**Issue by zouri** [groove-x/mqtt_bridge#57]
hi, I didn't find the option to turn off serialization when I checked the readme, is there a feature for this, thanks

**Comment by ledmonster** [comment]
@zouri 
Sorry for replying late. You can define passthrough serializer, and configure it in config file.

in your `someapp/someutil.py`:

```
def serialize(value):
    return value

def deserialize(value):
    return value
```

and you can configure it in config file like this:

```
serializer: someapp.someutil:serialize
deserializer: someapp.someutil:deserialize
```
