### ISSUE TITLE
data queue in ROS with MQTT client

### ISSUE THREAD

**Issue by Carlzhangk** [groove-x/mqtt_bridge#58]
I upload the data from ROS to cloud by MQTT client. Can gRPC Service stop consuming messages from ROS  when the communication is broken and ROS queue the messages until communication is reestablished ?

I am in Ubuntu 18.04 Melodic.

**Comment by ledmonster** [comment]
Unfortunately, it seems that MQTT doesn't have a queuing functionality.

- https://stackoverflow.com/questions/64941441/how-can-i-queue-messages-in-mqtt
